---
  title: "Modelisation Grassland avec retro action Caribu"
output: html_document
---

Note : Ce fichier n'est peut être pas tout à fait en accord avec la dernière version des fichiers cependant le principe des calculs n'a pas été changé.



  
But :   
Le fichier "l-egume_Caribu_Feedback.py" permet de lancer le model de legumineuse Grassland provenant de Lpy grâce à Python.


Nb : Les fonctions utilisés dans le fichier "Compar_Voxel_Caribu.py" sont les mêmes qui seront présentée si dessous mais ce fichier ne prend pas en compte la rétroaction par caribu et utilise les données provenant du calcul de rayonnement par Voxel.


On importe tout d'abord les differentes bibliotheques dont caribu pour le lance de rayon; generateScene pour pouvoir lancer le fichier de modelisation step by step, et la library Fonct_Comp qui sera decrite fonction par fonction tout au long de cette presentation.
```{python}

from numpy import *
from generateScene import *
import Fonct_Comp as Fc
from openalea.lpy import *
from openalea.plantgl.all import *
#Imports Caribu

from params_Ciel import*
from alinea.caribu.CaribuScene import CaribuScene
from alinea.caribu.sky_tools import GenSky, GetLight, Gensun, GetLightsSun
from alinea.caribu.caribu_shell import *
```


Pour cela, on importe tout d'abord le fichier LPY ainsi que le fichier de positionnement des plants de pois (maximum de plantes : 64) puis on lance la fonction Init_Lpy.


```{python}


path_ = os.path.dirname(os.path.abspath(legume.__file__))  # local absolute path of L-egume
lpy_filename = path_+'\l-egume.lpy'

path_pois = path_+'\Photomorph_caribu\input\Position_Pois.csv'
fichier_pois = loadtxt(path_pois, skiprows=1, delimiter=';')

runL,lsys, axiom, nbplantes = Fc.Init_Lpy(lpy_filename=lpy_filename, fichier_pois=fichier_pois)
```



La fonction  Init_Lpy permet d'initialiser la scene en fonction des positions de plantes selectionne dans le fichier excel "Position_Pois.csv". On reconstitu un axialTree et une cartographie des plantes que l'on viens injecter dans le Lsystem avant de lancer les premières etapes qui permettent la depose des graines et la preparation de la scene.


```{python}

def Init_Lpy(lpy_filename, fichier_pois):

    lsys = Lsystem(lpy_filename)

    # Definir carto et Nombre plantes

    nbplantes = len(fichier_pois)  # Doit etre moins que 64 plantes !!!!!
    lsys.nbcote = int(sqrt(nbplantes))

    # Pattern & sol
    lsys.cote = 55
    lsys.nbplantes = nbplantes


    a = AxialTree()
    a.append(lsys.attente(1))

    lsys.cartographie = []

    for i in range(0, nbplantes):
        x = fichier_pois[i][0]
        y = fichier_pois[i][1]

        lsys.cartographie.append(array([x, y, 0.]))
        a.append(lsys.Sd(i))

    lsys.axiom = a
    axiom = lsys.axiom
    lstring = lsys.derive(axiom, 25)
    axiom = lstring

    runL = run(lsys, axiom=axiom, nbstep=1)


    return runL,lsys, axiom, nbplantes

```




"Etape bouclées": Les étapes suivantes seront effectué un nombre de fois a defnir par l'utilisateur par la variable nb_iter.

A la suite de cette initialisation, on utilise donc la fonction run() pour effectuer chaque etape en prenant en arguement le run precedent pour l'argument lsys, et axiom et en lui donnant une valeur de step par défault a 1.

A partir de l'objet runL, on pourra sortir la scene s_leg qui nous servira pour la suite.
L'objet runL est composé de :
-runL[0]: l'axialTree
-runL[1]: le lsystem


```{python}
nb_iter = 180

for i in range(nb_iter):
    runL = run(runL[1], axiom=runL[0], nbstep=1)
    
    s_leg = runL[1].sceneInterpretation(runL[0]).deepcopy()

```




La suite du programme utilise principalement des fonctions de la libraire "Fonct_Comp.py".

A partir de la scene et du runL donné en argument, la fonction PrepareScene permet tout d'bord d'effectuer un trie sur la première scene afin de supprimer objets qui ne sont pas important dans les calculs caribu (racines, taux d'humidite dans le sol ...)

Durant ce trie, des dictionnaires sont crée afin d'être utilisé par la suite:

Dico_Apex_ID : permet de retrouver les ID correspondant aux apex dans la scene
Dico_conv : permet de passer des ID de la nouvelle scenes a ceux de l'ancienne
Dico_In, Dico_Pet,Dico_Stp : Comme Dico_Apex_ID, permet de retrouver les ID correspondant aux internoeuds, petioles et 'Stp', l'information des coordonnées de la bases des organes y est aussi enregistré
s_leg2 : c'est la scene épurée (on y change le sol pour que les capteurs virtuels soient bien placé et non enterré)

Par ailleurs au court de cette fonction, les objets sont renommée suivant le code de canestrad en fonction de si l'objet est une tige ou une feuille ce qui permet par la suite d'attribuer des propriétés optiques distinctes.

```{python}

def PrepareScene(scene,runL):

    sc = runL[0]
    s_leg2 = Scene()
    s_leg = scene

    xy = runL[1].cote

    #points = [(0, 0, 0),(xy,0,0), (xy,xy,0),(0,xy,0)]
    points = [(0, 0, 0), (0, 0, 0), (0, 0, 0), (0, 0, 0)]
    normals = [(0, 0, 1) for i in range(4)]
    indices = [(0, 1, 2, 3)]
    sol = QuadSet(points, indices, normals, indices)

    Dico_conv = {}

    nb_tri = 0

    # Pour le sol
    esp_opt = 000000000000
    n_plt = 0
    tp_org = 000000
    count_sh = esp_opt + n_plt + tp_org + nb_tri
    nb_tri += 1
    count_ID = 0


#Commente pour supprimer sol
    s_leg2.add(Shape(geometry=sol, id=count_ID, appearance=s_leg[0].appearance))
    s_leg2[count_ID].setName(str(count_sh))
    Dico_conv[count_ID] = 0
    count_ID += 1

    nb_tri = 0
    m = 0
    nump = 0

    Dico_Pet = {}
    Dico_In = {}
    Dico_Stp = {}
    Dico_Apex_ID = {}

    for x in s_leg:
        if x.id != s_leg[0].id and x.id != s_leg[1].id:

            nump = runL[0][x.id][0]

            if (sc[x.id].name == 'Pet'):
                liste = []
                liste.append(nump)
                liste.append(x.id)

                xa = runL[0][x.id + 1][0]
                ya = runL[0][x.id + 1][1]
                za = runL[0][x.id + 1][2]

                liste.append(xa)
                liste.append(ya)
                liste.append(za)

                if (xa < 0 or ya < 0 or x > 55 or ya > 55):
                    liste.append(-1)
                else:
                    liste.append(0)

                Dico_Pet[count_ID] = liste

            if (sc[x.id].name == 'In'):
                liste = []
                liste.append(nump)
                liste.append(x.id)

                liste.append(runL[0][x.id - 1][0])
                liste.append(runL[0][x.id - 1][1])
                liste.append(runL[0][x.id - 1][2])

                Dico_In[count_ID] = liste

            if (sc[x.id].name == 'A'):
                name_A = str(sc[x.id][0])+'_'+str(sc[x.id][1])+str(sc[x.id][5])
                Dico_Apex_ID[name_A] = x.id

            if (sc[x.id].name != 'solxy' and sc[x.id].name != 'p' and sc[x.id].name != 'RLAP' and sc[
                x.id].name != 'RS' and sc[x.id].name != 'RLB' and sc[x.id].name != 'RA' and sc[x.id].name != 'In'):

                if (sc[x.id].name == 'A' or sc[x.id].name == 'Stp' or sc[x.id].name == 'Pet'):  # Feuille
                    esp_opt = 100000000000
                    n_plt = 100000 + 100000 * nump
                    tp_org = 00000
                    count_sh = esp_opt + n_plt + tp_org + nb_tri
                    nb_tri += 1

                    if (sc[x.id].name == 'Stp'):
                        liste = []
                        liste.append(nump)
                        liste.append(x.id)
                        liste.append(count_sh)

                        Dico_Stp[count_ID] = liste


                if (sc[x.id].name == 'S' or sc[x.id].name == 'Lf' or sc[x.id].name == 'In'):  # Tige
                    esp_opt = 100000000000
                    n_plt = 00000 + 100000 * nump
                    tp_org = 10000
                    count_sh = esp_opt + n_plt + tp_org + nb_tri
                    nb_tri += 1

                s_leg2.add(Shape(geometry=x.geometry, id=x.id, appearance=x.appearance))
                s_leg2[count_ID].setName(str(count_sh))

                Dico_conv[count_ID] = x.id

                count_ID += 1


    return Dico_Apex_ID, Dico_conv, Dico_In, Dico_Pet, Dico_Stp, s_leg2

```



Dans le code principal on a alors : 

```{python}

    Dico_Apex_ID, Dico_conv, Dico_In, Dico_Pet, Dico_Stp, s_leg2 =Fc.PrepareScene(scene=s_leg, runL=runL)


    Dico_val = {}

    for x in Dico_Pet:
        Dico_val[x] = Dico_Pet[x]
    for x in Dico_In:
        Dico_val[x] = Dico_In[x]

```

Le dico_val permet simplement de regrouper les deux dico In et Pet en un seul.

Suite a cela, nous pouvons alors preparer les dictionnaires de capteurs virtuels utilisé par le model de rayonnement caribu. C'est le but de la fonction  create_Sensors qui prend en argument le runL et redonne en sortie le Dico_Sensors utilisable dans l'argument sensors de caribu.


Le principe actuel de la fonction est le suivant: 
on crée une scene de capteur en fonction des données de la scene provenant du runL puis on extrait les coordonnées des triangles de la scenes puis on les mets en formes afin de pouvoir utiliser le dico dans la fonction caribu. 
La fonction "create_Sensors_V2"  utilise la fonction  "create_LstVox_V1" qui permet, avec en argument le Dico_Val de creer des capteurs virtuels seulement où nous avons beosins des valeurs c'est a dire a l'emplacement des organes 


Fonction create_LstVox_V1 : 
```{python}



def create_LstVox_V1(runL,Dico_val,nbplantes):

    xyz = runL[1].dxyz
    pattern8 = runL[1].pattern8
    origin_grid = runL[1].origin_grid
    na = runL[1].na

    Dico_ParTresh = runL[1].Dico_ParTresh

    lstParTresh = {}
    count = 0
    for x in range(0,nbplantes):

        for z in Dico_ParTresh[x]['A']:
            xvox = Dico_ParTresh[x]['A'][z][0][0]
            yvox = Dico_ParTresh[x]['A'][z][0][1]
            zvox = Dico_ParTresh[x]['A'][z][0][2]
            numVox = [xvox, yvox, zvox]
            lstParTresh[count] = numVox
            count += 1

        for z in Dico_ParTresh[x]['B']:
            z = z.split()
            xB = float(z[1])
            yB = float(z[2])
            zB = float(z[3])
            placement = array([xB, yB, zB])
            vox = WhichVoxel(placement, origin_grid, na, xyz)
            lstParTresh[count] = vox
            count += 1

        for z in Dico_ParTresh[x]['A2']:
            xvox = Dico_ParTresh[x]['A2'][z][0][0]
            yvox = Dico_ParTresh[x]['A2'][z][0][1]
            zvox = Dico_ParTresh[x]['A2'][z][0][2]



            numVox = [xvox,yvox,zvox]
            lstParTresh[count] = numVox
            count += 1


    Lst_Vox = {}
    for k in Dico_val:
        xa = Dico_val[k][2]
        ya = Dico_val[k][3]
        za = Dico_val[k][4]
        placement = array([xa, ya, za])
        vox = WhichVoxel(placement, origin_grid, na, xyz)
        Lst_Vox[k] = vox

    for count in lstParTresh:
        Lst_Vox[k+1+count] = lstParTresh[count]

    return  Lst_Vox
```


Fonction create_Sensors_V2 :
```{python}




def create_Sensors_V2(runL,Dico_val,nbplantes):


    xyz = runL[1].dxyz
    pattern8 = runL[1].pattern8
    origin_grid = runL[1].origin_grid
    na = runL[1].na
    Lst_Vox = create_LstVox_V1(runL,Dico_val,nbplantes)


    s_capt = Scene()

    x = xyz[0]
    y = xyz[1]
    z = xyz[2]

    points = [(0, 0, 0),(x,0,0), (x,y,0),(0,y,0)]
    normals = [(0, 0, 1) for i in range(4)]
    indices = [(0, 1, 2, 3)]

    carre = QuadSet(points, indices, normals, indices)

    ID_capt = 1
    dico_translat = {}
    dico_IDtoVox = {}
    dico_VoxtoID = {}

    for l in Lst_Vox:

        i = Lst_Vox[l][0]
        j = Lst_Vox[l][1]

        if (Lst_Vox[l][2] != -1):
            k = len(runL[1].res_rfr) -1 - Lst_Vox[l][2]
        else :
            k = k+1#k = Boite la plus haute de la plante ????


        tx = i * x
        try :
            dico_VoxtoID[i] == {}
        except:
            dico_VoxtoID[i] = {}

        ty = j * y
        try :
            dico_VoxtoID[i][j] == {}
        except:
            dico_VoxtoID[i][j] = {}

        tz = k * z
        try:
            dico_VoxtoID[i][j][k] == {}
        except:
            dico_VoxtoID[i][j][k] = []

        dico_VoxtoID[i][j][k].append(ID_capt)

        Vox = Translated(geometry=carre, translation=(tx, ty, tz))
        s_capt.add(Shape(geometry=Vox, id=ID_capt))

        liste = []
        liste.append(tx)
        liste.append(ty)
        liste.append(tz)
        dico_translat[ID_capt] = liste

        liste = []
        liste.append(i)
        liste.append(j)
        liste.append(k)
        dico_IDtoVox[ID_capt] = liste

        ID_capt += 1

        #ajout face sup
        tz = (k+1) * z
        try:
            dico_VoxtoID[i][j][k+1] == {}
        except:
            dico_VoxtoID[i][j][k+1] = []

        dico_VoxtoID[i][j][k+1].append(ID_capt)

        Vox = Translated(geometry=carre, translation=(tx, ty, tz))
        s_capt.add(Shape(geometry=Vox, id=ID_capt))

        liste = []
        liste.append(tx)
        liste.append(ty)
        liste.append(tz)
        dico_translat[ID_capt] = liste

        liste = []
        liste.append(i)
        liste.append(j)
        liste.append(k)
        dico_IDtoVox[ID_capt] = liste

        ID_capt += 1


    #Viewer.display(s_capt)



    #Ajout des capteurs verticaux
    x = xyz[0]
    y = xyz[1]
    z = xyz[2]
    points = [[(0, 0, 0), (x, 0, 0), (x, 0, z), (0, 0, z)], [(0, y, 0), (0, y, z), (x, y, z), (x, y, 0)], [(0, 0, 0), (0, y, 0), (0, y, z),(0, 0, z)], [(x, 0, 0),(x, y, 0), (x, y, z),(x, 0, z)]]
    normals = [(0, 0, 1) for i in range(4)]
    indices = [(0, 1, 2, 3)]

    for m in Lst_Vox:

        i = Lst_Vox[m][0]
        j = Lst_Vox[m][1]
        k = len(runL[1].res_rfr) - Lst_Vox[m][2] -1

        tx = i * x
        ty = j * y
        tz = k * z
        for n in range(0, 4):
            dico_VoxtoID[i][j][k].append(ID_capt)
            carre = QuadSet(points[n], indices, normals, indices)

            Vox = Translated(geometry=carre, translation=(tx, ty, tz))
            s_capt.add(Shape(geometry=Vox, id=ID_capt))

            liste = []
            liste.append(tx)
            liste.append(ty)
            liste.append(tz)
            liste.append(n)
            dico_translat[ID_capt] = liste

            liste=[]
            liste.append(i)
            liste.append(j)
            liste.append(k)
            liste.append(n)

            dico_IDtoVox[ID_capt] = liste

            ID_capt += 1




    #Preparation capteurs
    pt_lst = s_capt[1].geometry.geometry.pointList
    idx_lst = s_capt[1].geometry.geometry.indexList

    Dico_Sensors = {}

    for x in s_capt:

        for i in range(0, len(idx_lst)):

            x11 = pt_lst[idx_lst[i][0]][0] + dico_translat[x.id][0]
            y11 = pt_lst[idx_lst[i][0]][1] + dico_translat[x.id][1]
            z11 = pt_lst[idx_lst[i][0]][2] + dico_translat[x.id][2]

            x12 = pt_lst[idx_lst[i][1]][0] + dico_translat[x.id][0]
            y12 = pt_lst[idx_lst[i][1]][1] + dico_translat[x.id][1]
            z12 = pt_lst[idx_lst[i][1]][2] + dico_translat[x.id][2]

            x13 = pt_lst[idx_lst[i][2]][0] + dico_translat[x.id][0]
            y13 = pt_lst[idx_lst[i][2]][1] + dico_translat[x.id][1]
            z13 = pt_lst[idx_lst[i][2]][2] + dico_translat[x.id][2]

            tple1 = []
            triangle = []
            tple1.append((x11, y11, z11))
            tple1.append((x12, y12, z12))
            tple1.append((x13, y13, z13))
            triangle.append(tple1)

            x21 = pt_lst[idx_lst[i][0]][0] + dico_translat[x.id][0]
            y21 = pt_lst[idx_lst[i][0]][1] + dico_translat[x.id][1]
            z21 = pt_lst[idx_lst[i][0]][2] + dico_translat[x.id][2]

            x22 = pt_lst[idx_lst[i][2]][0] + dico_translat[x.id][0]
            y22 = pt_lst[idx_lst[i][2]][1] + dico_translat[x.id][1]
            z22 = pt_lst[idx_lst[i][2]][2] + dico_translat[x.id][2]

            x23 = pt_lst[idx_lst[i][3]][0] + dico_translat[x.id][0]
            y23 = pt_lst[idx_lst[i][3]][1] + dico_translat[x.id][1]
            z23 = pt_lst[idx_lst[i][3]][2] + dico_translat[x.id][2]

            tple2 = []
            tple2.append((x21, y21, z21))
            tple2.append((x22, y22, z22))
            tple2.append((x23, y23, z23))
            triangle.append(tple2)

            Dico_Sensors[x.id]= triangle


    return Dico_Sensors, dico_VoxtoID, dico_IDtoVox, s_capt





```





En sortie de la fonction on recupere le dictionnaire permettant les capteurs virtuels dans caribu mais on obtiens aussi la scene s_capt afin de pouvoir, si on le souaite visualiser l'emplacement des capteurs.
On a aussi deux dico qui permettent de passer des voxels aux ID des triangles et inversement.


Les voxels representes les pavés de capteur et leur emplacement tel que le voxel [3,5,0] est le voxel n°3 sur x n°5 sur y n°0 sur z. Indépendament de la dimension. 
C'est le même système qui est utilisé dans les calculs de rayonnement sous Lpy et ce qui permet ainsi la comparaison entre les deux models.



Afin de finir de preparer les données pour lancer le calcul de rayonnement on a la fonction Opt_And_Pattern qui attribut a chaque objet de la scene des propriétés optiques en fonction de si c'est un sol, une tige ou une feuille. Cette fonction sort aussi le pattern qui permet par la suite de lancer caribu en mode infinity (Cette fonctionnalité n'est pas possible avec les capteurs pour le moment)


```{python}


def Opt_And_Pattern(scene,xmax,ymax):

    # Definition des propietes optiques des feuilles et tiges
    opt = {'rs': {}, 'rc': {}}

    for obj in scene:
        if obj.name[0] != '0':
            if (obj.name[7] == '1'):
                opt['rc'][obj.id] = (0.10, 0.07, 0.10, 0.07)
                opt['rs'][obj.id] = (0.41, 0.43, 0.41, 0.43)

            if (obj.name[7] == '0'):
                opt['rc'][obj.id] = (0.10, 0.07)
                opt['rs'][obj.id] = (0.41, 0.43)

        # Propriete sol :
        if (obj.name[0] == '0'):
            opt['rc'][obj.id] = (0.1, )
            opt['rs'][obj.id] = (0.1, )

    # Definition du patern
    pat = (0, 0, xmax, ymax)


    return pat, opt



```



Enfin, on définit le rayonnement lumineux et on lance les calculs Caribu :

```{python}

    #Definition du pattern et des proprietes optique
    s = s_leg2
    pat, opt = Fc.Opt_And_Pattern(scene=s, xmax=lsys.cote, ymax=lsys.cote)

    #Calculs Caribu Direct
    #Soleil vertical
    soleil = [(1.0, (0., -0.0, -1))]

    cc_scene = CaribuScene(scene = s, opt = opt, light = soleil, pattern = pat)
    _, aggregated_direct = cc_scene.run(direct = False, infinite = False, split_face = True,sensors=Dico_Sensors)


    #Resultats
    Dico_ValCapt_Direct_Rc = aggregated_direct['rc']['sensors']['Ei']
    Dico_ValCapt_Direct_Rs = aggregated_direct['rs']['sensors']['Ei']
```






Suite a ces calculs on peut alors preparer les dico de réponses que nous injectons dans le lsystem avec de lancer la prochaine étape de croissance.
```{python}
    #Prepa Dico de reponse
    Dico_rep, Dico_PARif = Fc.Dico_Reponse(Dico_val, runL, Dico_ValCapt_Direct_Rc, Dico_ValCapt_Direct_Rs, dico_VoxtoID, nbplantes)
    Dico_rep_PAR = Fc.PrePa_Reponse_PAR_Tresh(aggregated_direct, runL, dico_VoxtoID, Dico_Apex_ID)

    #injection
    runL[1].Dico_rep = Dico_rep
    runL[1].Dico_rep_PAR = Dico_rep_PAR
    runL[1].Dico_PARif = Dico_PARif
```
    
    
    
    
La fonction Dico_Reponse a pour ambition d'utiliser les données de caribu dans le modele lpy. Pour cela, on prend chaque organes utilisant des calculs de rayonnement (Dico_Val) dans leur calculs de longueur (dl / photomoph dans le model grassland).
Avec les données demplacement des organes on recupere dans quel voxel l'organe se situe et on prend les données des capteurs virtuels de caribu simulant aussi des voxel.
Le dico de réponse est ensuite construit de telle manière que l'on a les coordonnées de l'organe nous donnant la valeur de zeta correspondante. 
```{python}
#FeedBack donnee caribu sur Lpy
def Dico_Reponse(Dico_val, runL, Dico_ValCapt_Direct_Rc, Dico_ValCapt_Direct_Rs, dico_VoxtoID, nbplantes):


    origin_grid = runL[1].origin_grid
    xyz = runL[1].dxyz
    na = runL[1].na

    Dico_rep = {}
    Dico_PARif = {}

    for nump in range(0,nbplantes+1):
        Dico_rep[nump] = {}
        Dico_PARif[nump] = {}


    lstId = []
    for k in Dico_val:

        xa = Dico_val[k][2]
        ya = Dico_val[k][3]
        za = Dico_val[k][4]
        placement = array([xa, ya, za])
        vox = WhichVoxel(placement, origin_grid, na, xyz)

        LstId_Capt = dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - 1 - vox[2]]
        # Ajout face du dessus
        try:
            LstId_Capt.append(dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - vox[2]][0])
        except:
            pass

        LstId_Capt = unique(LstId_Capt)

        LstId_Capt = unique(LstId_Capt)
        face = 0
        sommeZeta = 0
        for Id_Capt in LstId_Capt:
            Rc = Dico_ValCapt_Direct_Rc[Id_Capt]
            Rs = Dico_ValCapt_Direct_Rs[Id_Capt]
            Zeta = Rc / Rs
            sommeZeta += Zeta
            face += 1

            #Zeta = schnute(Rc)

        Zeta = sommeZeta / face
        # Ecriture des resultats
        nump = Dico_val[k][0]

        Dico_rep[nump][str(xa)] = {}
        Dico_rep[nump][str(xa)][str(ya)] = {}
        Dico_rep[nump][str(xa)][str(ya)][str(za)] = Zeta

        Dico_PARif[nump][str(xa)] = {}
        Dico_PARif[nump][str(xa)][str(ya)] = {}
        Dico_PARif[nump][str(xa)][str(ya)][str(za)] = Rc


    return Dico_rep, Dico_PARif



```
    
    
    
    
La fonction PrePa_Reponse_PAR_Tresh a pour ambition d'effectuer  d'utiliser les données de caribu dans le modele lpy.
Cependant ici, les organes concernée sont les apex et les bourgeons et le paramètres en question influence la ramification (sauf sur le pois). 
On prepare alors le dico de réponse pour les apex et les bourgeons en fonction du rayonnement dans le voxel dans lequel ils se situent (cette information provient d'un dictionnaire crée dans le lsystem puisque les apex secondaire A2 et les bourgeons ne sont pas interprété et donc abscent de ). 
Cependant pour les objets A  présent dans la scene on utilise le rayonnement arrivant directement sur l'objet.
  Le dico de réponse est ensuite construit de telle manière que l'on a les coordonnées de l'organe nous donnant la valeur de PAR (Rc) correspondante. 
```{python}
def PrePa_Reponse_PAR_Tresh(aggregated_direct, runL, dico_VoxtoID, Dico_Apex_ID):

    Dico_ParTresh = runL[1].Dico_ParTresh
    xyz = runL[1].dxyz
    surfaceVox = xyz[0] * xyz[1]
    Dico_ValCapt_Direct_Rc = aggregated_direct['rc']['sensors']['Ei']

    Dico_Direct_Rc = aggregated_direct['rc']['Ei_sup']

    Normalis = runL[1].meteo_j['I0']


    Dico_Rep = {}
    for nump in Dico_ParTresh :
        Dico_Rep[nump] = {}
        Dico_Rep[nump]['A'] = {}
        Dico_Rep[nump]['A2'] = {}
        Dico_Rep[nump]['B'] = {}

    for nump in Dico_ParTresh:
        try:

            LstID = Dico_ParTresh[nump]['A']
            for ID in LstID:
                try:
                    PAR = Dico_Direct_Rc[Dico_Apex_ID[ID]]
                    Dico_Rep[nump]['A'][ID] = PAR * Normalis * 2 # Probleme cari
                except:
                    vox = [Dico_ParTresh[nump]['A'][ID][0][0], Dico_ParTresh[nump]['A'][ID][0][1],Dico_ParTresh[nump]['A'][ID][0][2]]
                    LstId_Capt = dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - 1 - vox[2]]
                    # Ajout face du dessus
                    LstId_Capt.append(dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - vox[2]][0])
                    LstId_Capt = unique(LstId_Capt)
                    PAR = 0
                    for Id_Capt in LstId_Capt:
                        Rc = Dico_ValCapt_Direct_Rc[Id_Capt]
                        PAR += Rc

                    PAR = PAR /len(LstId_Capt)
                    Dico_Rep[nump]['A'][ID] = PAR * Normalis

        except:
           pass


        LstID = Dico_ParTresh[nump]['A2']
        for ID in LstID:

            try :

                vox = [Dico_ParTresh[nump]['A2'][ID][0][0], Dico_ParTresh[nump]['A2'][ID][0][1], Dico_ParTresh[nump]['A2'][ID][0][2]]
                LstId_Capt = dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - 1 - vox[2]]
                # Ajout face du dessus
                LstId_Capt.append(dico_VoxtoID[vox[0]][vox[1]][len(runL[1].res_rfr) - vox[2]][0])
                LstId_Capt = unique(LstId_Capt)
                PAR = 0
                for Id_Capt in LstId_Capt:
                    Rc = Dico_ValCapt_Direct_Rc[Id_Capt]
                    PAR += Rc

                PAR = PAR /len(LstId_Capt)

                Dico_Rep[nump]['A2'][ID] = PAR * Normalis

            except:
                pass

        LstID = Dico_ParTresh[nump]['B']
        for ID in LstID:
            try:
                vox = [Dico_ParTresh[nump]['B'][ID][0][0], Dico_ParTresh[nump]['B'][ID][0][1],0 ]
                LstId_Capt = dico_VoxtoID[vox[0]][vox[1]][0]
                # Ajout face du dessus
                LstId_Capt.append(dico_VoxtoID[vox[0]][vox[1]][0][0])
                LstId_Capt = unique(LstId_Capt)
                PAR = 0
                for Id_Capt in LstId_Capt:
                    Rc = Dico_ValCapt_Direct_Rc[Id_Capt]
                    PAR += Rc

                PAR = PAR /(len(LstId_Capt))

                Dico_Rep[nump]['B'][ID] = PAR * Normalis

            except:
                pass

    return Dico_Rep
    
    
```
    
    
    
    
    
    
    
    
    
Cette partie de code permet de faire une sortie utilisable sous excel afin de comparer les données récoltée sur un organe avec les calculs de rayonnement caribu et la valeur du voxel correspondant à l'organe en question
```{python}

    Dico_Compare = Fc.CompareVoxCaribu(Dico_val, runL, aggregated_direct, Dico_conv)
    fout = open('Compare_Voxel_CaribuOrgane.dat', 'a')
    for k in Dico_Compare:
        fout.write("%s;%s;%s;%s;%s;%s;%s \n" % (k, Dico_Compare[k][0], Dico_Compare[k][1], Dico_Compare[k][2], Dico_Compare[k][3], Dico_Compare[k][4], Dico_Compare[k][5]  ))
        
```



La fonction CompareVoxCaribu est la suivante: 

```{python}



def CompareVoxCaribu(Dico_val, runL, aggregated_direct, Dico_conv):

    origin_grid = runL[1].origin_grid
    xyz = runL[1].dxyz
    na = runL[1].na
    sc = runL[0]

    Dico_Rc = aggregated_direct['rc']['Ei_sup']
    Dico_Rs = aggregated_direct['rs']['Ei_sup']

    Dico_return = {}

    for k in Dico_val:

        xa = Dico_val[k][2]
        ya = Dico_val[k][3]
        za = Dico_val[k][4]
        placement = array([xa, ya, za])
        vox = WhichVoxel(placement, origin_grid, na, xyz)

        #Zeta Caribu Organe
        Id_Org = Dico_conv[k]
        Rc = Dico_Rc[Id_Org]
        Rs = Dico_Rs[Id_Org]

        Zeta = Rc / Rs

        # Zeta Lpy
        RFR = runL[1].res_rfr[vox[2]][vox[1]][vox[0]]
        ResTrans = runL[1].res_trans[vox[2]][vox[1]][vox[0]]


        liste = []
        liste.append(Id_Org)
        liste.append(sc[Id_Org].name)
        liste.append(RFR)
        liste.append(ResTrans)
        liste.append(Rc)
        liste.append(Zeta)

        Dico_return[k] = liste




    return Dico_return

```



Arrivé ici, le programme a fini une boucle et peut alors lancer le prochain step.


Afin de comparer les scenes Grassland avec voxel et Grassland avec Caribu on pourra crée une scene avec la rétroaction sous "AppelLpy_V2_Feedback.py" et une sous "AppelLpy.py" .









NOTA BENE :

Dans la library Fonct_Comp, on retrouve aussi les fonctions suivante : 




La fonction WichVoxel. Cette fonction permet de trouver dans quel voxel se situe les coordonnées de l'organe donné en entrée 
```{python}


def WhichVoxel(p, origin_grid, na, dxyz):
    """ en z, id=0 = haut du couvert """
    p1_rel = p - origin_grid
    vox = [int(p1_rel[0]//dxyz[0]), int(p1_rel[1]//dxyz[1]), int(-p1_rel[2]//dxyz[2])] #// division entiere

    #test si dans grille et sinon retouve indice correspondant
    test = [0 <= vox[0] <na[0], 0 <= vox[1] <na[1], 0 <= vox[2] <na[2]]
    if test != [True,True,True]:#si hors grille
        #recup les indices du fautif
        matches = [i for i in range(3) if test[i]==False]
        #faire le calcul du bon id equivalent
        for i in matches:
            if i!=2: #x,y -> couvert infini
                vox[i] = vox[i]%na[i] # marche pour > et <0 et na[i]=1
            else: #z ->
                if vox[i]<0:#au dessus: met dans la derniere strate
                    vox[i] = 0
                else: #en dessous: met dans la strate au dessus du sol
                    vox[i] = na[i]-1
    return vox

```





La fonction schnute a pour interet de calculer une valeur de Zeta pour une valeur de rayonnement Transmis donnée. C'est la fonction utilisé dans le model de voxel.
```{python}


def schnute(x,a=3.09,b=1.59,c=0,d=1.12,x1=0.,x2=2.):
    """fonction schnute generale appliquee a x"""
    Y=pow((pow(c,b)+(pow(d,b)-pow(c,b)))*((1-exp(-a*(x-x1)))/(1-exp(-a*((x2-x1))))),(1/b))
    return Y
    
    
```





La fonction Sky_turtle6 est une fonction utilisé pour crée un ciel diffus utilisable dans caribu à la place de soleil pour le model de lumière. Le model turtle6 est le même que celui utilisé dans le modele de rayonnement Voxel quand le model est sur diffus.
```{python}

def Sky_turtle6():
    # Calcul poids ciel 5 direction
    sky_list = []

    ls_poids = [1. / 6.] + [5. / (6. * 4)] * 4
    alfa_turtle6 = 0.4637
    effet_sin = [sin(pi / 2)] + [sin(alfa_turtle6)] * 4
    x = array(ls_poids) * effet_sin
    ls_poids = x / sum(x)

    Azym = [0, 0, 90, 180, 270]

    for i in range(0, 5):
        azimuth = Azym[i]
        Energie = ls_poids[i]

        if i != 0:
            x_dir = cos(radians(azimuth)) * sin(alfa_turtle6)
            y_dir = sin(radians(azimuth)) * sin(alfa_turtle6)
            z_dir = cos(alfa_turtle6)
        else:
            x_dir = 0
            y_dir = 0
            z_dir = 1

        t_sky = tuple((float(Energie), tuple((float(x_dir), float(y_dir), float(-z_dir)))))

        sky_list.append(t_sky)

    return sky_list
```













